### ISSUE TITLE
Can I change the IP address?

### ISSUE THREAD

**Issue by jeena** [half2me/embeddedfun#1]
I'm logged in in my camera and I'd like to change the IP address but if I change it in /mnt/mtd/Config/network then it is changed back after reboot.

**Comment by half2me** [comment]
If you use the configuration software, I'm pretty sure you can change IP settings from DHCP configured, to static IP. As I don't have the device anymore that I used for the demo, I don't remember exactly how the network configuration was setup, but usually it is similar to most linux setups.

**Comment by jeena** [comment]
I can't because it is Windows only, so I hoped because you've poked around in it you perhaps found a way. But I'll poke around a bit more myself. Thanks for uploading the demo here, it was fun to read!

**Comment by half2me** [comment]
Config partition should hold all configuration data, so try looking around there...
